trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    destinationFolder: '$(Build.SourcesDirectory)'
    cleanDestinationFolder: false
- task: Maven@3
  inputs:
    mavenPomFile: '$(System.DefaultWorkingDirectory)/pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

